name: Build switch-library-manager

# On master and manually
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Setup astilectron
        run: |
          go get -u github.com/asticode/go-astilectron-bundler/...
          go install github.com/asticode/go-astilectron-bundler/astilectron-bundler

      - name: Bundle
        run: ~/go/bin/astilectron-bundler

      - name: Zip the MacOS release
        run: |
          cd output/darwin-amd64
          zip -q -X -r Switch-Library-Manager-${{ env.GITHUB_REF }}-MacOS.zip Switch-Library-Manager.app/
          cd ../..

      - name: Zip the Linux release
        run: |
          cd output/linux-amd64
          zip -q -X Switch-Library-Manager-${{ env.GITHUB_REF }}-Linux.zip Switch-Library-Manager
          cd ../..

      - name: Zip the Windows release
        run: |
          cd output/linux-amd64
          zip -q -X Switch-Library-Manager-${{ env.GITHUB_REF }}-Windows.zip Switch-Library-Manager.exe
          cd ../..

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: none
        with:
          args: output/*/*.zip